### ISSUE TITLE
On "compact display" net values have always 3 digits

### ISSUE THREAD

**Issue by michaltrzcinski** [paradoxxxzero/gnome-shell-system-monitor-applet#186]
On idle is like that:
Download: 000kb
Upload: 000kb

On use:
Download: 020kb
Upload: 003kb

Gnome 3.6.2

Edit: I see now... it is a _pad function for compact style only. Mayby put it in net configuration?

**Comment by franglais125** [comment]
I see that this was introduced 5 years ago in [8301dce6ba07934225f0f47f114c6b125a312fc4].

@boul51 Is there any reason to do it like that? This is a long shot!

**Comment by boul51** [comment]
Yes, I made this padding to prevent the top bar contents on the left of the monitor to move when the network speed changes.
(Well it depends on the position of your monitor and other stuff, but I prefer having items with static width)

**Comment by michaltrzcinski** [comment]
After 5 years, i'm fine with this. I'm used to it ;)

**Comment by franglais125** [comment]
@boul51 Thanks for getting back to me on such an old issue!

Ah, I see! I was looking at the menu items, and not the top bar. Any idea why this is needed for the "Net" text, and not for others?

**Comment by boul51** [comment]
On my side I usually just show text in top items for net and disk throughputs.
Disk usage text is typically x.yMB, and sometimes (but rarely) becomes xx.yMB,
which is only one digit difference and doesn't happen much.
On the other hand, network can change from something like 0kB to 312kB in just a few seconds and very frequently, which is more annoying, because the CPU and memory graphs, and my workspace in indicator, which are on the left of the network text are moving each times this happens.
