### ISSUE TITLE
Seems to cause serious system lag

### ISSUE THREAD

**Issue by fastcat** [paradoxxxzero/gnome-shell-system-monitor-applet#235]
Using this extension seems to frequently cause gnome-shell (and thus the entire X environment due to compositing) to pause for 5-20 seconds at a time every few minutes.

I noticed the memory leak issue already here, and thought that maybe gnome shell having to swap in and out was part of the problem.

However, restarting the gnome shell so that the leaking was gone does not make the pauses go away.

Disabling this extension made the pauses stop.

Note, related to info on the memory leak ticket: I'm not using an nVidia GPU on this system -- Intel HD Graphics here.

**Comment by rzippert** [comment]
I've posted an update on issue #202 that seems to relate with this one too. I suggest @fastcat to check that out...

**Comment by fastcat** [comment]
I didn't have i8k stuff installed when I first hit this, and when I later installed it, I had already uninstalled this extension due to its rampant problems.  Having i8k going caused plenty of issues by itself, so I uninstalled it.  I don't use a Dell any more, so that is moot now, but then I also don't use this extension any more because of this problem.

**Comment by joseangelsanchez** [comment]
Hi there! I love this extension but had to remove it because of repeated annoying lags. The good news is I found what was causing this by manually querying fan speed (cat /sys/class/hwmon/hwmon1/fan1_input): it hangs half a second my computer each query. Deactivating showing all fan related stuff stops querying the sensor an solved this problem for me... at least I have all other monitor graphs working. Tried to use i8kutils and it got worse! Uninstalled and happy again :)

Dell Vostro 3360, Debian 8, Gnome 3.18.1, a81d1c0800401033a563235f920655a936c907b06t

**Comment by return42** [comment]
> @fastcat, could this issue be a duplicate of #202?
> Yes, don't know how I missed that when looking to file this one. 

This issue is fixed in master since PR #497 is merged. Can you please test current master and close this issue? / Thanks!

**Comment by fastcat** [comment]
I uninstalled this extension years ago, and have since left the job where I had a setup that triggered this issue.  I don't have any handy means to test this now, as a result.

Sorry :(

**Comment by return42** [comment]
>  I don't have any handy means to test this now, as a result. Sorry :(

Don't apologize for that, that's okay. Anyway, if it's not reproducible for you, then may I ask you to close this issue?  We have so many open issues that I would like  to concentrate on those that are currently reproducible.  / Thanks!

**Comment by fastcat** [comment]
:+1:
