### ISSUE TITLE
The monitor applet polls the network as disk IO through gvfs, making the rest of the system freeze

### ISSUE THREAD

**Issue by nekohayo** [paradoxxxzero/gnome-shell-system-monitor-applet#263]
As seen in https://bugzilla.gnome.org/show_bug.cgi?id=698137#c2 and explained in https://bugzilla.gnome.org/show_bug.cgi?id=741998

Turns out that this extension hammers the system trying to get disk IO stats (even if the display is turned off in the panel), resulting in Nautilus not showing a file transfer progress dialog and pretty much the whole desktop locking up for the duration of the transfer.

**Comment by lantw44** [comment]
It seems the problem is caused by the synchronous `query_filesystem_info` call. The call on a remote file system can hang when the network is slow or unavailable

**Comment by darkxst** [comment]
@lantw44, Have you actually confirmed this somwhow? That should only be called when a mount is added/removed, it should not be getting called everytime the graphs refresh, if it is that needs to be fixed also. Still would be nicer to convert to async calls.

I always assumed it was caused by GTop.glibtop_get_fsusage which is also sync, but there is no async alternative available. That said though if it is reading from /proc/ sync call should be safe enough here (not actually checked that however).

**Comment by lantw44** [comment]
Sorry, no, it was not confirmed ... The real cause is GTop.glibtop_get_fsusage. I will try whether there is an alternative ...

**Comment by darkxst** [comment]
libgtop does not have an async api unfortunately. Perhaps it worth checking if usage can be collected somehow via Gio/Glib API's
