### ISSUE TITLE
Disk graph ignores LVM activity

### ISSUE THREAD

**Issue by louisvd** [paradoxxxzero/gnome-shell-system-monitor-applet#277]
The Disk Activity tab only accesses the traditional type of disk.  My LVM volumes don't get detected by it.  Could you fix this to include them? 

Thanks for a WONDERFUL extension.

**Comment by magik6k** [comment]
It should be doable via /proc/diskstats file, at least it's what iostat uses. To see how it works do 'strace iostat'

**Comment by gtristan** [comment]
I updated the patch here: https://bugzilla.gnome.org/show_bug.cgi?id=160441

As the currently submitted patch was both an eyesore, and did not work properly due to uninitialized variables... with patch applied the disk I/O works beautifully. Please test and let us know how it works for you with your comments on the upstream libgtop bug !

Only problem now, is that this extension only shows statistics for my / but no other volumes :)

**Comment by gtristan** [comment]
Sorry ... this is a duplicate bug for issue 97... is it not ? Shouldn't we close this as a dup ?

**Comment by darkxst** [comment]
Yes probably, I haven't really had time to maintain this extension much anymore unfortunately, but I do merge pull requests when they come in.

**Comment by franglais125** [comment]
I think this can be closed, as a fix was already merged in the duplicate issue.

**Comment by franglais125** [comment]
Fixed in https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/pull/280.
