### ISSUE TITLE
Gnome 3.21.90

### ISSUE THREAD

**Issue by blinoff82** [paradoxxxzero/gnome-shell-system-monitor-applet#315]
Dear developer, your app has stopped running on Gnome 3.21.90. Please check.

**Comment by brianjmurrell** [comment]
3.22 also

**Comment by Aaronik** [comment]
I've been running 3.18 on ubuntu 16.04 since it came out, and this applet has not worked at all, through multiple installation methods and a half year of updates. In the distant past this worked wonderfully for me, so I hold out hope that it'll work for me some time in the future as well. I'm sure it won't be checked, but it fails silently for me every time.

**Comment by chrisspen** [comment]
3.22 is currently supported in master, which I'm currently running. Can you confirm this?

**Comment by brianjmurrell** [comment]
Yeah, master works in 3.22.  Time to get an update up to the GNOME Extensions website?

**Comment by chrisspen** [comment]
@darkxst, I see you currently have ownership of the account on extensions.gnome.org. Could you give me publication access, or would you like to push up a new release?

**Comment by darkxst** [comment]
On 11/12/16 08:20, Chris Spencer wrote:
>
> @darkxst <https://github.com/darkxst>, I see you currently have 
> ownership of the account on extensions.gnome.org. Could you give me 
> publication access, or would you like to push up a new release?
>
>
I would be happy to let you have access, but I don't know the process 
for setting that. Any idea who is maintaining e.g.o site these days?
In the meanwhile also happy to push a new release up!

**Comment by franglais125** [comment]
@chrisspen @darkxst FWIW, I've been using the current master for a few hours now, with now visible issues, and no new errors in the logs (fewer in fact).

In any case, even if bugs may have been introduced, at this point system-monitor is not even installable for many people (unless they know how to do it manually), due to the old metadata.json. I'm sure it is worthwhile uploading a new version soonish.

**Comment by p91paul** [comment]
@darkxst @chrisspen the only way to perform an ownership transfer on extensions.gnome.org is to contact a reviewer. @darkxst can possibly find an email address on his old "extension accepted" emails; or he can perform one last upload on e.g.o. asking ownership transfer in review comments. The last option is that either of you contact me (you just accepted a pull request from me, reading the commits from a desktop client you'll find my email) and I'll give you a reviewer's address. I dislike posting emails here in comments, sorry ;D.

**Comment by franglais125** [comment]
Hey @darkxst @p91paul @chrisspen, any news on this? It would be nice to have a new version submitted to e.g.o.

I just submitted an extension for review, so I can leave a note to the reviewer saying to take a look at this thread or something like that.

@chrisspen do you have an account on e.g.o.?

**Comment by chrisspen** [comment]
I have an account, but I don't have access to this extension there.

**Comment by chrisspen** [comment]
@darkxst, If you're ok with transferring e.g.o maintainership to me, could you please send an email to security@gnome.org (and CC me), asking them to make the switch? My username there is "Cerin". I'm not sure who else to contact, but that seems like the most applicable option as listed at https://www.gnome.org/contact/.

**Comment by maweki** [comment]
I don't know how far this is gone but please post your request to the gnome-shell mailing list with some kind of proof that the previous maintainer either agrees or is unreachable and you don't intend to do "harm" (like showing some PRs you'd like to merge).

Once this is all done and ownership is transfered, you can upload new extensions. Since I am doing the reviews, it is much faster for me to review a few small changes one after another instead of a single big one.

**Comment by darkxst** [comment]
yes, I approve of the maintainership on e.g.o being transferred to @chrisspen.

**Comment by nE0sIghT** [comment]
@chrisspen 

I set you as maintainer of extension at e.g.o.

**Comment by chrisspen** [comment]
This should now be resolved by #335.
