### ISSUE TITLE
doesn't draw graphs while screen is locked

### ISSUE THREAD

**Issue by brianjmurrell** [paradoxxxzero/gnome-shell-system-monitor-applet#329]
When I unlock my screen, the graphs are empty and just starting fresh rather than having been continually populated while the screen was locked.

Sometimes it's useful to see what the state was prior to unlocking the screen.

**Comment by chrisspen** [comment]
I can't reproduce this. When I lock my screen, the graphs continue to populate. I'm running Ubuntu 16 with latest extension code from github.

What version of OS and Gnome are you running? What version of the extension do you have installed?

**Comment by franglais125** [comment]
@chrisspen just to make sure: so if you unlock your screen the graphs are fully drawn?

Every time I lock/unlock, the graphs are empty and start to be redrawn, just like when you open a new session.

**Comment by chrisspen** [comment]
Yes, the graphs are not cleared for me.

**Comment by franglais125** [comment]
Huh, that's a nice feature to have, heh.

I experience the same thing as @brianjmurrell, but it's always been like that for me. If you check the logs, the extension gets disabled when locking, and enabled again when unlocking the screen.

@chrisspen your graph isn't empty, but is it refreshed when the screen is locked? Or is it just showing the information from before the lock?

**Comment by brianjmurrell** [comment]
Here's a screenshot of my system monitor applet a few seconds after unlocking the screen:

![status](https://cloud.githubusercontent.com/assets/559317/21082106/544ae4fa-bfa2-11e6-85ac-a8d42c9ff44d.png)

As you can see, the graphs are starting out fresh.

**Comment by darkxst** [comment]
when you lock the screen all extensions get disabled (atleast when you are using gdm). So from a system-monitor point of view unlocking is essentially creating a new session. So if you want the history to persist you would essentially need to save a snapshot of the data, but that wont show you what happened while the screen was locked. 

The only way to achieve the latter would be to split out the performance monitoring code into a daemon that runs as its own process and just have the gnome-shell extension rendering the data. That would seem like a lot of work, but would also have some performance benefits. System-monitor currently hammers the gnome-shell main thread, since gnome-shell is only single threaded.

**Comment by chrisspen** [comment]
@darkxst, Ah, that might explain why I'm not seeing any problem. I'm running lightdm, not gdm. So, a work-around would be to switch display managers. This is probably the long-term solution since it's unlikely anyone's going to invest in the significant amount of work required to fix this relatively minor issue.

**Comment by brianjmurrell** [comment]
Or it could be explained to the gdm maintainers that this behaviour causes this bug.

Any idea why this is unique to gdm?

**Comment by darkxst** [comment]
The gdm lock screen is a special gnome-shell session. For security reason no third party code is allowed to run within the lock screen. So essentially this behaviour is by design.

lightdm support is basically just a big hack in the gnome-shell so doesnt have the same issues.

**Comment by darkxst** [comment]
@chrispen Splitting it out into a daemon may be worth it for performance reasons, but clearly not worth the effort to get a history of what happened while screen lock

**Comment by franglais125** [comment]
For anyone interested, locally I run this branch https://github.com/franglais125/gnome-shell-system-monitor-applet/tree/dont_disable, which doesn't disable the extension when locking/unlocking. We can't upstream this, as it goes against the policy of disabling/enabling when locking/unlocking, but locally you can take this approach.

**Comment by ZimbiX** [comment]
There's an official way of doing this now! :tada: - [Session modes](https://gjs.guide/extensions/topics/session-modes.html)

I've [just tried it out](https://github.com/ZimbiX/gnome-shell-system-monitor-applet/commit/9a4084b940b7d330e1e6ec854adf938b18704ea6), and it works well. It'd probably be good to have a setting for it though.
