### ISSUE TITLE
Compact Display mode - Disk text size a little bir bigger 

### ISSUE THREAD

**Issue by ceyhunnabiyev** [paradoxxxzero/gnome-shell-system-monitor-applet#380]
On the  following picture,  size of  MiB/s is a little bir bigger:

![b8f5873e-24ec-11e7-9eba-101d102c9012](https://user-images.githubusercontent.com/5506156/27536522-9f4e81b8-5a80-11e7-8ef0-6ab4df7b0339.png)

**Comment by franglais125** [comment]
I added a fix for this in my big "style" PR: https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/pull/375, here: [9d3fbcb839a652bbdef0960c60a7fcd8b132c42b]

**Comment by franglais125** [comment]
@chrisspen any chance you might have a look at the PRs? It would be a shame for them to rot there. It's been over a month, and if I have to look back a them in some months from now, it will be much harder for me to fix or give feedback on whatever issues we might find, as I won't remember as well all the details.

Also, we might need to update the travis check. The latest commit I added is not passing the test due to a problem with the build system:
```
W: http://ppa.launchpad.net/builds/sphinxsearch-rel21/ubuntu/dists/trusty/Release.gpg: Signature by key 2FE7BA61B28B34B7A2B749A2B9D8946B16932B16 uses weak digest algorithm (SHA1)
E: Failed to fetch https://debian.neo4j.org/repo/stable/Packages.gz  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.

The command "sudo apt-get -yq update" failed and exited with 100 during .

Your build has been stopped.
```

**Comment by franglais125** [comment]
This was fixed in https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/pull/375.
