### ISSUE TITLE
Please consider tagging a new release

### ISSUE THREAD

**Issue by highvoltage** [paradoxxxzero/gnome-shell-system-monitor-applet#406]
Hi! Thanks for all the work on this extension, there has been a lot of updates since version 32, would you consider tagging a new release? Thanks!

**Comment by franglais125** [comment]
My guess is that @chrisspen is waiting for further confirmation that there are no new issues on 3.26 (we had a rocky 3.24 transition).

I'd perhaps simply include the HiDPI fix I proposed in another issue before tagging.

**Comment by franglais125** [comment]
@chrisspen any news on this?

**Comment by chrisspen** [comment]
Is it ready to go? We've had a few PRs merged since a tag was last requested.

**Comment by franglais125** [comment]
I've been using git master on 3.26 for over a month with no problems. I'd suggest including:

#404, #407 and #413

**Comment by chrisspen** [comment]
Done. Any last requests?

**Comment by franglais125** [comment]
Thanks a lot! I think we are good to go with the changes so far.

**Comment by chrisspen** [comment]
Ok, release 33 is tagged on Github and has been submitted to EGO.

**Comment by chrisspen** [comment]
@franglais125 Thanks for all your work on the bug fixes for this release.

**Comment by franglais125** [comment]
Thanks @chrisspen for the new tag and upload!

Perhaps you can add something like this to the extension website (to address the review):

`NVIDIA GPU usage: requires the nvidia-smi tool`

For the next tag, I'll try to add a dynamic check for this cli tool (just like we do for GTop, etc.), so that it tells the user that the dependency is missing.

Btw, (@highvoltage) for packaging purposes, perhaps you can add "Recommends:/Suggests:" on nvidia-smi (https://packages.debian.org/buster/nvidia-smi).
