### ISSUE TITLE
Extension crashes spontaneously

### ISSUE THREAD

**Issue by avevad** [paradoxxxzero/gnome-shell-system-monitor-applet#617]
The extension crashes sometimes without any reason. It just hangs and no information will be updated after it happens. It will work after restarting gnome shell (Alt + F2, "r" command), but it seems to happen too often. I don't know how to open extension logs, but `journalctl -xe` had provided me some information:
<pre>июн 10 12:14:57 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.</b></font>
июн 10 12:14:57 AVEVAD gnome-shell[2189]: == Stack trace for context 0x55d18360d6e0 ==
июн 10 12:14:57 AVEVAD gnome-shell[2189]: == Stack trace for context 0x55d18360d6e0 ==
июн 10 12:14:57 AVEVAD gnome-shell[2189]: == Stack trace for context 0x55d18360d6e0 ==
июн 10 12:14:57 AVEVAD gnome-shell[2189]: == Stack trace for context 0x55d18360d6e0 ==
июн 10 12:14:57 AVEVAD gnome-shell[2189]: == Stack trace for context 0x55d18360d6e0 ==
июн 10 12:14:57 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.</b></font>
июн 10 12:14:57 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.</b></font>
июн 10 12:14:57 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.</b></font>
июн 10 12:14:57 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.</b></font>
июн 10 12:14:57 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>Attempting to run a JS callback during garbage collection. This is most likely caused by destroying a Clutter actor or GTK widget with ::destroy signal connected, or using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked.</b></font>
июн 10 12:14:57 AVEVAD gnome-shell[2189]: == Stack trace for context 0x55d18360d6e0 ==
июн 10 12:14:57 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>The offending callback was AsyncReadyCallback().</b></font>
июн 10 12:14:57 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.</b></font>
июн 10 12:14:57 AVEVAD gnome-shell[2189]: == Stack trace for context 0x55d18360d6e0 ==
июн 10 12:14:57 AVEVAD gnome-shell[2189]: == Stack trace for context 0x55d18360d6e0 ==
июн 10 12:14:57 AVEVAD gnome-shell[2189]: == Stack trace for context 0x55d18360d6e0 ==
июн 10 12:14:57 AVEVAD gnome-shell[2189]: == Stack trace for context 0x55d18360d6e0 ==
июн 10 12:14:57 AVEVAD gnome-shell[2189]: == Stack trace for context 0x55d18360d6e0 ==
июн 10 12:14:57 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.</b></font>
июн 10 12:14:57 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.</b></font>
июн 10 12:14:57 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.</b></font>
июн 10 12:14:57 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.</b></font>
июн 10 12:15:00 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.</b></font>
июн 10 12:15:00 AVEVAD gnome-shell[2189]: == Stack trace for context 0x55d18360d6e0 ==
</pre>

**Comment by Avevad** [comment]
It had just crashed yet again and some more info appeared in logs:
<pre>июн 10 12:32:00 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.</b></font>
июн 10 12:32:00 AVEVAD gnome-shell[2189]: == Stack trace for context 0x55b64ea826e0 ==
июн 10 12:32:00 AVEVAD gnome-shell[2189]: #0   7fff743f7780 I   /home/avevad/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/extension.js:353 (19731b7efcb8 @ 418)
июн 10 12:32:00 AVEVAD gnome-shell[2189]: #1   7fff743f77d0 I   /home/avevad/.local/share/gnome-shell/extensions/system-monitor@paradoxxx.zero.gmail.com/extension.js:971 (19731b7f23d0 @ 155)
июн 10 12:32:00 AVEVAD gnome-shell[2189]: #2   7fff743f7810 I   self-hosted:1007 (2b0f29e974c0 @ 398)
июн 10 12:32:00 AVEVAD gnome-shell[2189]: == Stack trace for context 0x55b64ea826e0 ==
июн 10 12:32:00 AVEVAD gnome-shell[2189]: == Stack trace for context 0x55b64ea826e0 ==
июн 10 12:32:00 AVEVAD gnome-shell[2189]: == Stack trace for context 0x55b64ea826e0 ==
июн 10 12:32:00 AVEVAD gnome-shell[2189]: == Stack trace for context 0x55b64ea826e0 ==
июн 10 12:32:00 AVEVAD gnome-shell[2189]: == Stack trace for context 0x55b64ea826e0 ==
июн 10 12:32:00 AVEVAD gnome-shell[2189]: == Stack trace for context 0x55b64ea826e0 ==
июн 10 12:32:00 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>The offending signal was repaint on StDrawingArea 0x55b652002470.</b></font>
июн 10 12:32:00 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.</b></font>
июн 10 12:32:00 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.</b></font>
июн 10 12:32:00 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.</b></font>
июн 10 12:32:00 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.</b></font>
июн 10 12:32:00 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.</b></font>
июн 10 12:32:00 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.</b></font>
июн 10 12:32:00 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.</b></font>
июн 10 12:32:00 AVEVAD gnome-shell[2189]: == Stack trace for context 0x55b64ea826e0 ==
июн 10 12:32:00 AVEVAD gnome-shell[2189]: == Stack trace for context 0x55b64ea826e0 ==
июн 10 12:32:00 AVEVAD gnome-shell[2189]: == Stack trace for context 0x55b64ea826e0 ==
июн 10 12:32:00 AVEVAD gnome-shell[2189]: == Stack trace for context 0x55b64ea826e0 ==
июн 10 12:32:00 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.</b></font>
июн 10 12:32:00 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.</b></font>
июн 10 12:32:00 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.</b></font>
июн 10 12:32:00 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.</b></font>
июн 10 12:32:00 AVEVAD gnome-shell[2189]: == Stack trace for context 0x55b64ea826e0 ==
июн 10 12:32:05 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.</b></font>
июн 10 12:32:05 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>The offending signal was set-cursor-location on IBusPanelService 0x55b65245a1b0.</b></font>
июн 10 12:32:05 AVEVAD gnome-shell[2189]: == Stack trace for context 0x55b64ea826e0 ==
июн 10 12:32:05 AVEVAD gnome-shell[2189]: == Stack trace for context 0x55b64ea826e0 ==
июн 10 12:32:05 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.</b></font>
июн 10 12:32:05 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>The offending signal was set-cursor-location on IBusPanelService 0x55b65245a1b0.</b></font>
июн 10 12:32:06 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.</b></font>
июн 10 12:32:06 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>The offending signal was set-cursor-location on IBusPanelService 0x55b65245a1b0.</b></font>
июн 10 12:32:06 AVEVAD gnome-shell[2189]: == Stack trace for context 0x55b64ea826e0 ==
июн 10 12:32:06 AVEVAD gnome-shell[2189]: == Stack trace for context 0x55b64ea826e0 ==
июн 10 12:32:06 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.</b></font>
июн 10 12:32:06 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>The offending signal was set-cursor-location on IBusPanelService 0x55b65245a1b0.</b></font>
июн 10 12:32:06 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.</b></font>
июн 10 12:32:06 AVEVAD gnome-shell[2189]: == Stack trace for context 0x55b64ea826e0 ==
июн 10 12:32:06 AVEVAD gnome-shell[2189]: == Stack trace for context 0x55b64ea826e0 ==
июн 10 12:32:06 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>The offending signal was set-cursor-location on IBusPanelService 0x55b65245a1b0.</b></font>
июн 10 12:32:06 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.</b></font>
июн 10 12:32:06 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>The offending signal was set-cursor-location on IBusPanelService 0x55b65245a1b0.</b></font>
июн 10 12:32:07 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.</b></font>
июн 10 12:32:07 AVEVAD gnome-shell[2189]: == Stack trace for context 0x55b64ea826e0 ==
июн 10 12:32:07 AVEVAD gnome-shell[2189]: == Stack trace for context 0x55b64ea826e0 ==
июн 10 12:32:07 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>The offending signal was set-cursor-location on IBusPanelService 0x55b65245a1b0.</b></font>
июн 10 12:32:07 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.</b></font>
июн 10 12:32:07 AVEVAD gnome-shell[2189]: <font color="#D7D75F"><b>The offending signal was set-cursor-location on IBusPanelService 0x55b65245a1b0.</b></font>
</pre>

**Comment by avevad** [comment]
¯\_(ツ)_/¯ The issue disappeared on its own (maybe because of gnome update), closing.
