### ISSUE TITLE
Better CPU graph for multi-core

### ISSUE THREAD

**Issue by kevincox** [paradoxxxzero/gnome-shell-system-monitor-applet#648]
Right now there are two options for the CPU graph. 1 graph for total usage, or 1 graph per core.

I find that the total graph doesn't provide enough information for example one core at 100% is very different from all cores at 12% on an 8 core system. However the individual core graphs don't scale well with many core systems. It isn't uncommon to have a 16 or 32 core system these days. This takes up a lot of space in the toolbar or you need to have very narrow graphs.

It would be nice to have a mode that scales better with cores. My first thought is to do what gnome-system-monitor does and just draw all of the lines on the same graph. This works well but I can think of a couple of problems.

1. Different aesthetic from the different graphs.
2. Unclear how to show System/Nice/Iowait/User separately.

![image](https://user-images.githubusercontent.com/494012/101265533-36e8cf00-3715-11eb-8168-c97e1a2311e2.png)

Personally I would be fine with those downsides, but it would be interesting to discuss other options.

**Comment by FranklinYu** [comment]
#373 is about this idea explicitly. My concern is that tiny graphs with too many lines would be illegible; GNOME System Monitor is fine because its graphs are big. I have two more ideas:

 1. Only show physical cores. This cuts the number in half for some users.
 2. Show half of the cores in secondary inverted axes. This cuts the number in half for all users. They could be [growing against each other](https://i.stack.imgur.com/tfx5p.jpg) or [back-to-back](https://i.stack.imgur.com/GH3fg.png).

I have a hyper-threaded desktop, so having both implemented would be good enough for me.

**Comment by kevincox** [comment]
Ok, I'll copy my comment there and close this.
