### ISSUE TITLE
werid top bar text

### ISSUE THREAD

**Issue by vancez** [paradoxxxzero/gnome-shell-system-monitor-applet#685]
![2021-04-22_22-06](https://user-images.githubusercontent.com/40771709/115729127-bb33aa00-a3b7-11eb-8e4e-f98e84e1b0ff.png)
![2021-04-23_21-13](https://user-images.githubusercontent.com/40771709/115876528-0235a400-a479-11eb-8d85-ec3d97f13e48.png)

**Comment by fvdnabee** [comment]
I have the impression that the text is corrupted when the length of the number being displayed changes, so I'm running with the following patch (in order to get numbers to display at a fixed width via over-padding) and this has fixed the text corruption for me:
[net-padding.patch.txt](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/files/6715294/net-padding.patch.txt)

The coming days I'll try to monitor whether the corrupted text occurs. Note the patch above only targets the non-compact mode.

**Comment by biji** [comment]
sorry, is this issue resolved? Similiar issue happen to my extension

thanks

**Comment by rschupp** [comment]
> sorry, is this issue resolved? Similiar issue happen to my extension

@biji You mean biji/simplenetspeed#32? Look's definitely like the same problem. And no, not yet resolved.
Note that the purported fix in your issue ("use CSS min-width instead of width") does **not** help in our case (same goes for the patch by @fvdnabee), as system-monitor does not use width (neither does it help to increase min-width).

I suspect a bug in gnome-shell (40.3.1) or mutter.

**Comment by rschupp** [comment]
> I suspect a bug in gnome-shell (40.3.1) or mutter.

If I run gnome-shell with `CLUTTER_PAINT=disable-clipped-redraws` in the environment [1], the problem goes away.

[1] If your gnome-shell is started as a systemd user service, create a file `~/.config/systemd/user/org.gnome.Shell@wayland.service.d/debug.conf` with the following contents
```
[Service]
Environment="CLUTTER_PAINT=disable-clipped-redraws"
```

**Comment by ixevix** [comment]
Workaround seems to be working, though my service is:
`~/.config/systemd/user/org.gnome.Shell@x11.service.d/debug.conf`

**Comment by biji** [comment]
Probably you can participate in this issue:
https://gitlab.gnome.org/GNOME/mutter/-/issues/1943#note_1272458

**Comment by rschupp** [comment]
The patch in https://gitlab.gnome.org/GNOME/mutter/-/issues/1943#note_1272550 fixes it for me

**Comment by rschupp** [comment]
A fix for this mutter issue has been merged (https://gitlab.gnome.org/GNOME/mutter/-/commit/867db93043dd3c93d8ccb6cb197d4a3687d3a5e5), will be included in mutter release 41.
