### ISSUE TITLE
'make install' doesn't work after logout

### ISSUE THREAD

**Issue by sidt4** [paradoxxxzero/gnome-shell-system-monitor-applet#785]
1. Do `make install` and logout

2. The following is displayed in the extensions app ( an update is available and logout prompt )

![status](https://user-images.githubusercontent.com/128038884/225979813-20fcc14c-fd66-4b4a-bc2f-0268e036a8f6.png)

3. Logout and login, you get the following error in extensions app and the extension doesn't load.

![error](https://user-images.githubusercontent.com/128038884/225979820-721f8118-e24d-4954-8a3e-e7b340015964.png)

**Comment by ZimbiX** [comment]
[As I said previously](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/782#issuecomment-1472182305):

> I use `VERSION=9999 make install` to prevent automatic 'updating' to the published version.

This is due to the default of the version in the [`metadata.json`](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/blob/21d7b4e7a03ec8145b0b90c4f0b15c27d6f53788/system-monitor%40paradoxxx.zero.gmail.com/metadata.json#L10) being -1, and Gnome Shell seeing any published version as an update over this.

**Comment by sidt4** [comment]
> VERSION=9999 make install

I tried that too.

But, I'll try again tomorrow and let you know.

**Comment by sidt4** [comment]
`VERSION=9999 make install` works fine.

**Comment by ZimbiX** [comment]
Maybe we should adjust the readme to say this
