### ISSUE TITLE
Disk I/O not showing

### ISSUE THREAD

**Issue by stefanheijnen** [paradoxxxzero/gnome-shell-system-monitor-applet#97]
Disk I/O is no longer showing on a fresh install of Mint 12. it was working on my previous Mint 12 setup. I tried both the Git and webupd8 version. Dependencies in the README are all met.  Any ideas?

http://imageshack.us/photo/my-images/580/screenshotat20120105112.png/

**Comment by gtristan** [comment]
Reposting here where I intended to post the comment:

I updated the patch here: https://bugzilla.gnome.org/show_bug.cgi?id=160441

As the currently submitted patch was both an eyesore, and did not work properly due to uninitialized variables... with patch applied the disk I/O works beautifully. Please test and let us know how it works for you with your comments on the upstream libgtop bug !

Only problem now, is that this extension only shows statistics for my / but no other volumes :)

**Comment by purpleidea** [comment]
The famous tvb to the rescue, awesome!
If you could test under LUKS+btrfs that would be nice too :)
Thanks

**Comment by ArnaudDovi** [comment]
@gtristan 
Works great thank you !
